//! Canonical manifest of `tests/command/status_wave0_test.rs` test names
//! (plan-20260714 §B.9).
//!
//! This constant is the single source of truth for the wave-0 status test
//! set: `compat_status_wave0_register` asserts bidirectional set equality
//! against `cargo test --test command_test -- --list` and strict
//! alphabetical ordering. Add or remove a test in the module and this list
//! together — never edit only one side.

pub const STATUS_WAVE0_TESTS: &[&str] = &[
    "api_warning_concurrent_isolated",
    "api_warning_no_global_exit_pollution",
    "api_warning_survives_await",
    "bare_null_emits_porcelain_v1",
    "bare_z_emits_porcelain_v1",
    "cached_conflicts_with_rename_flags",
    "chain_rename_default_untracked_d_and_question",
    "chain_rename_two_records",
    "check_dirty_ioblocked_does_not_mutate_cache",
    "cluster_stops_at_value_option",
    "core_quote_path_invalid_fail_closed",
    "exit_code_ioblocked_is_one",
    "exit_warning_over_dirty_cache_fallback",
    "find_renames_raw_grammar_and_last_wins",
    "generate_short_status_entries_api",
    "global_short_value_contains_z_not_format",
    "human_rename_long_format",
    "ioblocked_scan_does_not_replace_dirty_cache",
    "json_inexact_reordered_score_100",
    "json_inexact_spanhash_score_floor",
    "json_io_blocked_is_clean_false",
    "json_io_blocked_non_utf8_path_reversible",
    "json_io_blocked_schema_snapshot",
    "json_rename_rm_partial_chain",
    "json_repo_relative_from_subdir",
    "json_warnings_schema_snapshot",
    "main_scan_ioblocked_keeps_prior_sibling_json",
    "no_head_staged_rename",
    "non_utf8_path_skips_rename_not_status",
    "normalize_ignores_diff_pathspec_status",
    "object_read_corrupt_blob_skips_inexact_only",
    "object_read_missing_blob_skips_inexact_only",
    "pathspec_old_only_new_only_matrix",
    "porcelain_quote_path_utf8_non_ascii",
    "porcelain_v1_rename_output_stays_add_delete",
    "porcelain_v1_uses_rename_arrow_when_detected",
    "porcelain_v2_staged_rename_mode_hash_fields",
    "porcelain_v2_unmerged_u_line",
    "porcelain_v2_unstaged_dot_r_hash_fixup",
    "porcelain_v2_z_rename_record_nul_paths",
    "porcelain_z_non_utf8_base_status_raw_bytes",
    "probe_budget_bounds_wide_directory",
    "probe_complete_consumes_dir_marker",
    "probe_dest_rejects_ignored",
    "probe_dest_rejects_tracked_path",
    "probe_dir_eacces_fail_closed",
    "probe_directory_symlink_is_leaf",
    "probe_never_enters_libra_or_git_metadata",
    "probe_roots_exclude_only_repo_root",
    "probe_skipped_when_renames_disabled",
    "probe_skipped_when_untracked_disabled",
    "probe_truncated_keeps_dir_marker",
    "quote_path_always_escapes_tab",
    "rename_config_cli_find_renames_overrides_false",
    "rename_config_status_renames_false_disables",
    "rename_empty_file_exact_pair_only",
    "rename_exact_staged_detected_by_default",
    "rename_from_subdirectory_detected",
    "rename_inexact_content_change_detected",
    "rename_json_includes_score_and_side",
    "rename_limit_config_cascade",
    "rename_limit_warning_exit_nine_over_dirty",
    "rename_no_renames_flag_splits_add_delete",
    "rename_porcelain_v2_emits_rename_record",
    "rename_sha256_repo_detected",
    "rename_short_format_uses_arrow",
    "rename_untracked_config_cascade",
    "rename_untracked_true_uno_no_question_mark",
    "rename_untracked_true_uno_probe_success",
    "resolved_conflict_with_stage0_emits_no_u_line",
    "short_quote_path_core_false",
    "similarity_budget_warning",
    "st_bare_z_emits_porcelain_v1",
    "staged_rename_then_delete_emits_rd",
    "staged_rename_then_modify_emits_rm",
    "status_short_value_contains_s_not_short",
    "tracked_scan_eacces_partial_json",
    "tracked_unreadable_path_fails_closed_not_deleted",
    "unmerged_stage_presence_to_xy_mapping",
];
